package org.creditsms.plugins.paymentview.data.domain;

import javax.persistence.*;

import org.apache.commons.collections.functors.FalsePredicate;

import net.frontlinesms.data.EntityField;

/**
 * Data object representing a quick dial code. Quick dial codes are a representation of USSD
 * request strings. USSD is a stateless request response system used for transactions such as air 
 * time transfer, balance enquiry and accessing other services provided by the network operator. 
 * 
 * @author Emmanuel Kala
 *
 */

@Entity
@Table(uniqueConstraints={@UniqueConstraint(columnNames={QuickDialCode.FIELD_QUICK_DIAL_STRING, 
        QuickDialCode.FIELD_NETWORK_OPERATOR_ID})})
public class QuickDialCode {
//> CONSTANTS    
    /** Field name for {@link #quickDialString} */
    public static final String FIELD_QUICK_DIAL_STRING = "dial_string";
    /** Field name for {@link #quickDialDescription} */
    private static final String FIELD_QUICK_DIAL_DESCRIPTION = "description";
    /** Field name for {@link #networkOperator} */
    public static final String FIELD_NETWORK_OPERATOR_ID = "network_operator_id";
    /** Field name for {@link #responseType} */
    private static final String FIELD_RESPONSE_TYPE = "response_type";
    /** Field name for {@link #storeResponse} */
    private static final String FIELD_STORE_RESPONSE = "store_response";

//> ENUMS    
    /** Type of response returned by the USSD request */
    public enum ResponseType {
        TYPE_TEXT, TYPE_MENU
    }
    
    public enum Field implements EntityField<QuickDialCode> {
        /** Field mapping for {@link QuickDialCode#quickDialString} */
        DIAL_STRING("dial_string");
        
        private final String fieldName;
        
        Field (String fieldName) { this.fieldName = fieldName; }
        
        public String getFieldName () { return this.fieldName; }
    }
    
//> PROPERTIES
    @Id @GeneratedValue(strategy=GenerationType.IDENTITY) @Column(unique=true, nullable=false, updatable=false)
    private long id;
    
    /** Quick dial number */
    @Column(name=FIELD_QUICK_DIAL_STRING, nullable=false)
    private String quickDialString;
    
    /** Description of what the quick dial code does */
    @Column(name=FIELD_QUICK_DIAL_DESCRIPTION, nullable=false)
    private String quickDialDescription;
    
    /** Network operator for which this quick dial works*/
    @ManyToOne(targetEntity=NetworkOperator.class, optional=false)
    @JoinColumn(name=FIELD_NETWORK_OPERATOR_ID)
    private NetworkOperator networkOperator;
    
    /** Type of response returned by the USSD server */
    @Column(name=FIELD_RESPONSE_TYPE, nullable=false)
    private ResponseType responseType;
    
    /** Flags whether the USSD response is to be stored or not */
    @Column(name=FIELD_STORE_RESPONSE, nullable=false)
    private boolean storeResponse;

    /**
     * Empty constructor to allow for instantiation of an empty instance
     */
    public QuickDialCode () {
        
    }
    
    /**
     * Creates an instance of {@link QuickDialCode} and sets all its properties except for the id
     * The id is generated by the database once this instance is saved to the database
     * 
     * @param dialString Quick dial string for the quick dial code
     * @param description description of the quick dial code
     * @param operator {@link NetworkOperator} associated with the quick dial code
     * @param responseType Type of response returned by the USSD server
     */
    public QuickDialCode (String dialString, String description, NetworkOperator operator, ResponseType responseType) {
        setQuickDialString(dialString);
        setQuickDialDescription(description);
        setNetworkOperator(operator);
        setResponseType(responseType);        
    }
    
//> ACCESSORS
    /** Gets the unique ID of the quick dial code*/
    public long getId() {
        return id;
    }
    
    /** Gets the quick dial number */
    public String getQuickDialString() {
        return quickDialString;
    }
    
    /** Gets the description of the quick dial code */
    public String getQuickDialDescription() {
        return quickDialDescription;
    }
    
    /** Gets the network operator associated with this quick dial code */
    public NetworkOperator getNetworkOperator() {
        return networkOperator;
    }
    
    /** Gets the type of response returned by the USSD server when this quick dial code is issued */
    public ResponseType getResponseType(){
        return responseType;
    }
    
    /** Whether the response for the USSD request is to be stored */
    public boolean isStoreResponse() {
        return storeResponse;
    }
    
//> MUTATORS
    /**
     * Sets the quick dial string for this quick dial code
     * @param dialString
     */
    public void setQuickDialString(String dialString) {
        this.quickDialString = dialString;
    }
    
    /**
     * Sets the description of the quick dial code i.e. what the quick dial
     * code does
     * 
     * @param description
     */
    public void setQuickDialDescription(String description) {
        this.quickDialDescription = description;
    }
    
    /**
     * Sets the {@link NetworkOperator} associated with this quick
     * dial code
     * 
     * @param operator
     */
    public void setNetworkOperator(NetworkOperator operator) {
        this.networkOperator = operator;
    }
    
    /**
     * Sets the {@link ResponseType} for this quick dial code
     * @param response
     */
    public void setResponseType(ResponseType response) {
        this.responseType = response;

        // Only store responses for text type responses
        switch (response) {
        case TYPE_TEXT:
            storeResponse = true;
            break;
        default:
            storeResponse = false;
        }
    }
    
}